name: 'Docs Deploy'

on:
  release:
    types: ['published']

jobs:
  deploy:
    name: 'Deploy'
    runs-on: ubuntu-latest

    steps:
      - run: curl -X POST -d {} ${{ secrets.NETLIFY_BUILD_HOOK }}
